//const moduleData = require("./math");
// const { add, sub, multi, divide } = require("./math");
import { add, sub } from "./math";
// console.log(moduleData);
// console.log(moduleData.add(3, 4));
// console.log(moduleData.sub(3, 4));
console.log(add(3, 4));
console.log(sub(3, 4));
console.log(multi(3, 4));
console.log(divide(3, 4));
